version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "09:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - somewhatabstract

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "09:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - somewhatabstract
