version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - somewhatabstract
